### ISSUE TITLE
Does CRF layer support multi-label classification?

### ISSUE THREAD

**Issue by machanic** [createmomo/CRF-Layer-on-the-Top-of-BiLSTM#2]
My label is multi-label , it must predict a vector rather than a scalar label.
Does this CRF layer support this ? if don't, why?

**Comment by createmomo** [comment]
Hi, many thanks for your comment. The CRF layer discussed in this repository is the one for the named entity recognition problem in which each token only has one corresponding label. I think this is nor your problem which is a multi-label task. But I think you can try to define a specific loss function or borrow the idea of the CRF loss function and adapt/extend it to your own problem. Probably there has been some work/publications which have already proposed similar ideas for multi-label tasks.

**Comment by machanic** [comment]
I think maybe it is hard, maybe the log-likelihood and label dependency (transfer matrix) let CRF can only support single label, multi-label (vector) dependency is hard to capture, in my understanding

**Comment by ghost** [comment]
hi createmomo, thank you for your brief demo, but I still have a question to ask:
the xs variable, which is produced by lstm and init randomly in the demo,  is not be trained, 
should it be trained in  formal model?thanks

**Comment by createmomo** [comment]
@doggyChe hi doggyChe, many thanks for your reply. Your understanding is right. The LSTM network and CRF layer should be trained jointly. 

Because this demo and those blog posts focus on explaining how CRF layer works, there is no real LSTM network in the demo code. I just created some synthetic LSTM outputs and put them into CRF layer.
